from rest_framework import serializers
from core_upm.models import CodeArtifact,Project # الاستيراد من طبقة Models

class CodeArtifactSerializer(serializers.ModelSerializer):
    """
    Serializer for CodeArtifact listing/upload. 
    Uses storage_reference instead of code_content.
    """
    project_id = serializers.PrimaryKeyRelatedField(
        queryset=Project.objects.all(), source='project', write_only=True
    )
    project_name = serializers.CharField(source='project.project_name', read_only=True)
    
    class Meta:
        model = CodeArtifact
        fields = [
            'code_id', 'project_id', 'project_name', 'file_name', 
            'upload_date', 'code_language', 'code_version', 'storage_reference'
        ]
        # storage_reference is read-only here as it's generated by the service layer, not provided by the user
        read_only_fields = ['code_id', 'project_name', 'upload_date', 'storage_reference']



class CodeArtifactDetailSerializer(serializers.ModelSerializer):
    """
    Serializer to show full artifact details, including the storage reference.
    """
    project_name = serializers.CharField(source='project.project_name', read_only=True)

    class Meta:
        model = CodeArtifact
        fields = [
            'code_id', 'project', 'project_name', 'file_name', 'upload_date', 
            'code_language', 'code_version', 'storage_reference'
        ]
        read_only_fields = fields        